const products = [
  {
    id: 1,
    name: "Tropical Bloom Printed Shirt",
    price: 78,
    image: "images/n1.jpg",
    images: ["images/n1.jpg", "images/n2.jpg", "images/n3.jpg", "images/n4.jpg"],
    category: "Men's T-Shirt",
    description: "Bio-washed cotton tee for all-day comfort.",
    brand: "Adidas",
  },
  {
    id: 2,
    name: "Streetwear Hoodie",
    price: 99,
    image: "images/n2.jpg",
    images: ["images/n2.jpg", "images/n3.jpg", "images/n4.jpg", "images/n1.jpg"],
    category: "Men's T-Shirt",
    description: "Oversized hoodie with modern print.",
    brand: "Nike",
  },
  {
    id: 3,
    name: "Slim Fit Jeans",
    price: 89,
    image: "images/n3.jpg",
    images: ["images/n3.jpg", "images/n4.jpg", "images/n1.jpg", "images/n2.jpg"],
    category: "Men's T-Shirt",
    description: "Comfortable stretch jeans for daily wear.",
    brand: "Levi's",
  },
  {
    id: 4,
    name: "Basic White Tee",
    price: 45,
    image: "images/n4.jpg",
    images: ["images/n4.jpg", "images/n1.jpg", "images/n2.jpg", "images/n3.jpg"],
    category: "Men's T-Shirt",
    description: "Minimal white tee with soft texture.",
    brand: "Zara",
  },
  {
    id: 5,
    name: "Denim Jacket",
    price: 129,
    image: "images/f1.jpg",
    images: ["images/f1.jpg", "images/f2.jpg", "images/f3.jpg", "images/f4.jpg"],
    category: "Men's T-Shirt",
    description: "Vintage denim look with a modern fit.",
    brand: "H&M",
  },
  {
    id: 6,
    name: "Cargo Pants",
    price: 75,
    image: "images/f2.jpg",
    images: ["images/f2.jpg", "images/f3.jpg", "images/f4.jpg", "images/f1.jpg"],
    category: "Men's T-Shirt",
    description: "Multi-pocket cargo pants for utility and style.",
    brand: "Superdry",
  },
  {
    id: 7,
    name: "Graphic Hoodie",
    price: 110,
    image: "images/f3.jpg",
    images: ["images/f3.jpg", "images/f4.jpg", "images/f1.jpg", "images/f2.jpg"],
    category: "Men's T-Shirt",
    description: "Graphic print hoodie in breathable cotton.",
    brand: "Puma",
  },
  {
    id: 8,
    name: "Patterned Shirt",
    price: 65,
    image: "images/f4.jpg",
    images: ["images/f4.jpg", "images/f1.jpg", "images/f2.jpg", "images/f3.jpg"],
    category: "Men's T-Shirt",
    description: "Modern slim-fit shirt with subtle patterns.",
    brand: "Mango",
  },
  {
    id: 9,
    name: "Linen Shirt",
    price: 60,
    image: "images/n5.jpg",
    images: ["images/n5.jpg", "images/n6.jpg", "images/n7.jpg", "images/n8.jpg"],
    category: "Men's T-Shirt",
    description: "Lightweight linen shirt for summer comfort.",
    brand: "Uniqlo",
  },
  {
    id: 10,
    name: "Polo T-Shirt",
    price: 55,
    image: "images/n6.jpg",
    images: ["images/n6.jpg", "images/n7.jpg", "images/n8.jpg", "images/n5.jpg"],
    category: "Men's T-Shirt",
    description: "Classic polo with breathable fabric.",
    brand: "Lacoste",
  },
  {
    id: 11,
    name: "Oversized Sweatshirt",
    price: 95,
    image: "images/n7.jpg",
    images: ["images/n7.jpg", "images/n8.jpg", "images/n5.jpg", "images/n6.jpg"],
    category: "Men's T-Shirt",
    description: "Warm oversized sweatshirt in fleece.",
    brand: "GAP",
  },
  {
    id: 12,
    name: "Checked Shirt",
    price: 70,
    image: "images/n8.jpg",
    images: ["images/n8.jpg", "images/n5.jpg", "images/n6.jpg", "images/n7.jpg"],
    category: "Men's T-Shirt",
    description: "Casual shirt with modern check pattern.",
    brand: "Jack & Jones",
  },
  {
    id: 13,
    name: "Athletic Joggers",
    price: 85,
    image: "images/f5.jpg",
    images: ["images/f5.jpg", "images/f6.jpg", "images/f7.jpg", "images/f8.jpg"],
    category: "Men's T-Shirt",
    description: "Flexible joggers for workout and casual wear.",
    brand: "Adidas",
  },
  {
    id: 14,
    name: "Urban Track Pants",
    price: 90,
    image: "images/f6.jpg",
    images: ["images/f6.jpg", "images/f7.jpg", "images/f8.jpg", "images/f5.jpg"],
    category: "Men's T-Shirt",
    description: "Stylish track pants with zipper pockets.",
    brand: "Nike",
  },
  {
    id: 15,
    name: "Formal Blazer",
    price: 150,
    image: "images/f7.jpg",
    images: ["images/f7.jpg", "images/f8.jpg", "images/f5.jpg", "images/f6.jpg"],
    category: "Men's T-Shirt",
    description: "Elegant blazer for meetings and events.",
    brand: "Arrow",
  },
  {
    id: 16,
    name: "Classic Leather Jacket",
    price: 200,
    image: "images/f8.jpg",
    images: ["images/f8.jpg", "images/f5.jpg", "images/f6.jpg", "images/f7.jpg"],
    category: "Men's T-Shirt",
    description: "Premium leather jacket with timeless design.",
    brand: "Harley-Davidson",
  },
];
